release:
  script:
    - call tools\update_repos.bat
    - call tools\release.bat
  tags:
    - windows
  only:
    - web
  artifacts:
    paths:
      - release\killerbeez-*.zip
    expire_in: 1 week
